### PR TITLE
Ensure all examples work without sci unless mentioned otherwise

### LINKED ISSUE #723: generator sample error
I got error when I try the sample in generator part
```clojure
(require '[malli.generator :as mg]) 

(mg/generate
   [:and {:gen/fmap '(partial str "kikka_")} string?]
   {:seed 10, :size 10})
```
The error message
```
clojure.lang.ExceptionInfo: :malli.core/sci-not-available {:code (partial str "kikka_")}
{:type :malli.core/sci-not-available, :message :malli.core/sci-not-available, :data {:code (partial str "kikka_")}}
 at malli.core$_fail_BANG_.invokeStatic (core.cljc:138)
    malli.core$_fail_BANG_.invoke (core.cljc:136)
    malli.core$fn__22859$_fail_BANG___22860.invoke (core.cljc:2242)
    malli.core$fn__22859$eval__22866.invoke (core.cljc:2251)
    malli.generator$_create_from_fmap.invokeStatic (generator.cljc:261)
    malli.generator$_create_from_fmap.invoke (generator.cljc:259)
    malli.generator$_create.invokeStatic (generator.cljc:270)
    malli.generator$_create.invoke (generator.cljc:267)
    malli.generator$generator$fn__2045.invoke (generator.cljc:285)
    malli.core$_cached.invokeStatic (core.cljc:285)
    malli.core$_cached.invoke (core.cljc:282)
    malli.generator$generator.invokeStatic (generator.cljc:285)
    malli.generator$generator.invoke (generator.cljc:281)
    malli.generator$generate.invokeStatic (generator.cljc:291)
    malli.generator$generate.invoke (generator.cljc:287)
    campaign.import.common$eval2097.invokeStatic (NO_SOURCE_FILE:445)
    campaign.import.common$eval2097.invoke (NO_SOURCE_FILE:445)
    clojure.lang.Compiler.eval (Compiler.java:7194)
    clojure.lang.Compiler.eval (Compiler.java:7149)
    clojure.core$eval.invokeStatic (core.clj:3215)
    clojure.core$eval.invoke (core.clj:3211)
    nrepl.middleware.interruptible_eval$evaluate$fn__25097$fn__25098.invoke (interruptible_eval.clj:87)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$with_bindings_STAR_.invokeStatic (core.clj:1990)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1990)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    nrepl.middleware.interruptible_eval$evaluate$fn__25097.invoke (interruptible_eval.clj:87)
    clojure.main$repl$read_eval_print__9206$fn__9209.invoke (main.clj:437)
    clojure.main$repl$read_eval_print__9206.invoke (main.clj:437)
    clojure.main$repl$fn__9215.invoke (main.clj:458)
    clojure.main$repl.invokeStatic (main.clj:458)
    clojure.main$repl.doInvoke (main.clj:368)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:84)
    nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:56)
    nrepl.middleware.interruptible_eval$interruptible_eval$fn__25128$fn__25132.invoke (interruptible_eval.clj:152)
    clojure.lang.AFn.run (AFn.java:22)
    nrepl.middleware.session$session_exec$main_loop__25192$fn__25196.invoke (session.clj:202)
    nrepl.middleware.session$session_exec$main_loop__25192.invoke (session.clj:201)
    clojure.lang.AFn.run (AFn.java:22)
    java.lang.Thread.run (Thread.java:748)
```

### PR DESCRIPTION
**Pull request by vharmain**
Closes https://github.com/metosin/malli/issues/723

### CODE REVIEW

**Review by ikitommi — APPROVED** [review]
this would not require sci:

```clj
;; portable :gen/fmap
(mg/generate
  [:and {:gen/fmap (partial str "kikka_")} string?]
  {:seed 10, :size 10})
;; => "kikka_WT3K0yax2"
```

if you think so, we could add both examples for clarity. anyway 👍

**Comment by vharmain** [comment]
Good point! I adjusted it so that there are now both examples, first the "simple one" and then the portable one.

I hope it's clear enough that the first one will only work on the particular runtime and the quoted one can be serialized. 🤔 (I also hope that I got it right 😉)

**Comment by vharmain** [comment]
Hmm I think there's similar gotcha in `Multi schemas` section:

Any (serializable) function can be used for `:dispatch`:

```clojure
(m/validate
  [:multi {:dispatch 'first}
   [:sized [:tuple keyword? [:map [:size int?]]]]
   [:human [:tuple keyword? [:map [:name string?] [:address [:map [:country keyword?]]]]]]]
  [:human {:name "seppo", :address {:country :sweden}}])
; true
```

I guess also here unquoted one would work similarly.

**Comment by vharmain** [comment]
Actually, @ikitommi we should probably clarify in the README what are the limitations to functions in general
- when serialization is needed (sci)
- when no serialization is needed (will just about any function work..?)

**Comment by ikitommi** [comment]
Yes, all examples besides a specific sci-part could be without sci. Any function works in all places. Quoting is just a trick to get 'em serialized.

Feel free to tune the README however it's better.

**Comment by vharmain** [comment]
I went through all the examples `README.md` and changed them to work without sci when appropriate.

I also lifted commonly used `Address` schema to its own section because it's assumed in many examples across the README and earlier it was defined in a bit random place.

**Review by ikitommi — APPROVED** [review]
so good.

**Pull request merged**
