### PR TITLE
Add test for nested multi schema with decode/string

### PR DESCRIPTION
**Pull request by Deraen**
Why does this fail?

### CODE REVIEW

**Comment by ikitommi** [comment]
dispatch values are keywords (`:int`), but in values, they are strings (`"int"`). Try `[:multi {:dispatch :type} ["int" ...]]`

**Comment by Deraen** [comment]
That's why I'm using :decode/string.

It has worked in some other cases.

**Comment by Deraen** [comment]
The previous test cases also test `decode/string` to update value before dispatch.

But doesn't work with nested multi schemas.

**Comment by Deraen** [comment]
Oh, I need to of course decode values first. Seems to work here, something else broken on the real project.

**Comment by Deraen** [comment]
Okay, Malli itself works.

Reitit Malli coercion closes all the schemas, and that breaks `[:and multi [:map ...]]` case because maps on the both and branches will be closed.

**Pull request closed without merging**
