### PR TITLE
Replace one children :and with properties with :fn

### PR DESCRIPTION
**Pull request by Deraen**

### CODE REVIEW

**Comment by ikitommi** [comment]
`[:fn string?]` is not a real schema, it does not transform, convert to JSON Schema etc. These would be more idiomatic, in the order of idiomacy:

```clj
string?
-> [:schema {} string?]
-> [string? {}]

:string
-> [:string {}]
-> [:schema {} :string]
```

**Comment by Deraen** [comment]
Argh. The difference is really confusing.

**Comment by Deraen** [comment]
`[string? {}]` is also bad example because it takes different properties to `[:string ...]`

**Comment by ikitommi** [comment]
yes, the `string?`s should go, sugar leading to a dead-end.

**Pull request closed without merging**
