### PR TITLE
Distinguish between symbols and strings in humanize

### PR DESCRIPTION
**Pull request by frenchy64**
For clj use `pr-str`, for cljs use `str`.

### CODE REVIEW

**Comment by ikitommi** [comment]
Thanks!

**Comment by danielcompton** [comment]
@frenchy64 could you explain a bit more about why you made this change? Why can’t CLJ and CLJS both use pr-str?

We have CLJC tests which include Malli error messages. Now we need to use reader conditionals on the error message to have them pass in both CLJS and CLJ.

**Comment by frenchy64** [comment]
I'm told pr-str in cljs is too expensive to use because it pulls in too much code after minification.

-------- Original Message --------
On 6/1/24 03:51, Daniel Compton wrote:
@frenchy64 could you explain a bit more about why you made this change? Why can’t CLJ and CLJS both use pr-str?
We have CLJC tests which include Malli error messages. Now we need to use reader conditionals on the error message to have them pass in both CLJS and CLJ.

**Comment by liwp** [comment]
To close the loop here: we ended up overriding `malli.error/-pr-str` in our tests to get consistent output:

```clj
(t/use-fixtures
  :once
  (fn [f]
    (with-redefs [me/-pr-str pr-str]
      (f))))
```

A bit naughty, but keeps reader conditionals away from the tests.

**Pull request merged**
