### PR TITLE
Add :map qualified keyword child syntax

### PR DESCRIPTION
**Pull request by kwrooijen**
Fixes: https://github.com/metosin/malli/issues/14

### CODE REVIEW

**Comment by kwrooijen** [comment]
Maybe I could clean this up by creating a few predicate functions?
`-map-entry-qualified-keyword?`
`-map-entry-qualified-keyword-with-options?`
`-map-entry-regular?`
`-map-entry-regular-with-options?`

This might help the readability of the code. Right now it's just a bunch of predicates everywhere. We could also use these functions in both `-expand-key` and  `-valid-child?`.

**Comment by kwrooijen** [comment]
Applied my comment in the latest commit. It's a bit more code but I hope you can agree it's more organized as well.

**Comment by kwrooijen** [comment]
A thought: Would it be interesting to allow property inheritance?
Current:

``` clojure
;; Add to registry
(m/def ::id [int? {:description "Unique identifier"}])

[:map
 ::id]

;; Results in >>>

[:map 
 [::id nil [int? {:description "Unique identifier"}]]]
```

I can image that inheritance could be interesting in some cases.

``` clojure
;; Add to registry
(m/def ::id [int? 
  ^:inherit
  {:description "Unique identifier"}])

[:map
 ::id]

;; Results in >>>

[:map 
 [::id {:description "Unique identifier"} [int? {:description "Unique identifier"}]]]
```

Just an idea. But if you're interested, maybe we could create an issue for this?

**Comment by kwrooijen** [comment]
On the same topic as my last comment; I also noticed that this doesn't work:

```clojure
(def s1 [:map [:user/name {:default "Anonymous"} string?]])
(m/decode s1 {} mt/default-value-transformer)
;; >> {}
```

But this does:

```clojure
(def s2 [:map [:user/name [string? {:default "Anonymous"}]]])
(m/decode s2 {} mt/default-value-transformer)
;; >> {:user/name "Anonymous"}
```

Maybe you could also pass properties the other way around? Something like...

```clojure
[:map 
 [:user/name
  ^:provide
  {:default "Anonymous"}]]
```
That way you could add a default to the value from the map's perspective. You would be able to share types between maps, but they would have their own usage for them.

**Comment by ikitommi** [comment]
Will get back to this after #86 is resolved. Sorry for taking so long.

**Comment by ikitommi** [comment]
pulled the code into current (changed) master, but broke it. will fix. But nice using a local registry:

```clj
(-> [:schema {:registry {:user/id int?
                         :user/name string?
                         :user/gender [:enum "male" "female" "other"]}}
     [:map {:closed true}
      ;; naked references to registry
      :user/id
      :user/name
      ;; can be optional
      [:user/gender {:optional true}]
      ;; local
      [:skills [:set [:enum "clj" "cljs"]]]
      [:user/skills [:set [:enum "clj" "cljs"]]]]]
    (m/explain
      {:user/id 1
       :user/genderz ""})
    (me/with-spell-checking)
    (me/humanize))
;{:user/name ["missing required key"],
; :skills ["missing required key"],
; :user/skills ["missing required key"],
; :user/genderz ["should be spelled :user/gender"]}
```

**Comment by ikitommi** [comment]
merged in master via #239. Added some parsing tests and option to create `:map` without support of this. Thanks!

**Pull request closed without merging**
