### PR TITLE
renamed named variants of :cat, :alt and :or

### PR DESCRIPTION
**Pull request by ikitommi**
* `:cat*`, `:alt*`, `:or*` => `:cat-named`, `:alt-named`, `:or-named`

### CODE REVIEW

**Comment by ikitommi** [comment]
not 100% happy with either one.

**Comment by borkdude** [comment]
@ikitommi Maybe:

```
:catn, :altn, :orn 
``` 
?

**Comment by ikitommi** [comment]
@borkdude that's more concise. Was one of the original thoughts, but got buried. I think i's the best of the bunch.

**Comment by ikitommi** [comment]
changed to that. thanks!

**Pull request merged**
