### PR TITLE
map-of limit

### LINKED ISSUE #486: Add min/max properties to map-of
Is there a reason map-of shouldn't support these types of predicates?

### PR DESCRIPTION
**Pull request by bsless**
Add min/max properties to map-of like other collection schemas

Closes #486

### CODE REVIEW

**Comment by ikitommi** [comment]
Looks good. To make it complete:

* could you add a explain test (::m/limits) to document the new contract
* JSON Schema mappings (https://json-schema.org/understanding-json-schema/reference/object.html#size)
* Generator support for min & max

**Comment by bsless** [comment]
Will do, probably finish it tomorrow morning

**Comment by bsless** [comment]
> * could you add a explain test (::m/limits) to document the new contract

There might be a general problem there for collections which I'll fix along the way:
```
(me/humanize (m/explain (m/schema [:vector {:max 2} int?]) [1 2 3]))
["unknown error"]
```

**Comment by bsless** [comment]
Added limits explainer in 0a832a9, any comments regarding the wording and order of checks?

**Comment by bsless** [comment]
Alright, ready for another review

**Comment by ikitommi** [comment]
Looks good, thanks!!

**Pull request merged**
